// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo5p1_fVHcW-8N7njyP4_6yyTBk3JbZtg',
    appId: '1:729685841824:web:2a5129eab98b489fc3f6c5',
    messagingSenderId: '729685841824',
    projectId: 'flutter-3642f',
    authDomain: 'flutter-3642f.firebaseapp.com',
    databaseURL: 'https://flutter-3642f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-3642f.appspot.com',
    measurementId: 'G-RQQBLVBK46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQF3x_Hjdt1LdCXKnIPMXvUub3cvTG89k',
    appId: '1:729685841824:android:334fdd91d7a7156fc3f6c5',
    messagingSenderId: '729685841824',
    projectId: 'flutter-3642f',
    databaseURL: 'https://flutter-3642f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-3642f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUU3_aGkuSIQ5ItAKt--FLZbKaSoa-sqQ',
    appId: '1:729685841824:ios:4f9ecd984940615ec3f6c5',
    messagingSenderId: '729685841824',
    projectId: 'flutter-3642f',
    databaseURL: 'https://flutter-3642f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-3642f.appspot.com',
    iosBundleId: 'com.example.day1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo5p1_fVHcW-8N7njyP4_6yyTBk3JbZtg',
    appId: '1:729685841824:web:8eaeb38b97f107bcc3f6c5',
    messagingSenderId: '729685841824',
    projectId: 'flutter-3642f',
    authDomain: 'flutter-3642f.firebaseapp.com',
    databaseURL: 'https://flutter-3642f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-3642f.appspot.com',
    measurementId: 'G-HBM6LKLVNX',
  );

}